apiVersion: v1
kind: Service
metadata:
  name: ranger-admin
spec:
  selector:
    app: ranger-admin
  type: LoadBalancer
  ports:
  - name: adminport
    port: 6080
    targetPort: 6080
  - name: solrport
    port: 6083
    targetPort: 6083
